export const items = [
    {
    id:1,
    category: "mobile",
    title: " Apple iPhone 14",
    imgSrc: "https://m.media-amazon.com/images/I/716fAVud8PL._SL1500_.jpg",
    amazoneLink:"http://amzn.to/3PuckZp",
    description:"Apple iPhone 14 (128 GB) - Blue",
    price: " 89999",
    },
    {
        id:2,
        category: "mobile",
        title: " Apple iPhone 15",
        imgSrc: "https://m.media-amazon.com/images/I/71v2jVh6nIL._SL1500_.jpg",
        amazoneLink:"http://amzn.to/3PuckZp",
        description:"Apple iPhone 15 (256 GB) - Blue",
        price: " 99999",
        },
        {
            id:3,
            category: "laptop",
            title: " Hp",
            imgSrc: "https://m.media-amazon.com/images/I/61vGumezioL._SL1300_.jpg",
            amazoneLink:"http://amzn.to/3PuckZp",
            description:"Hp  (256 GB) - Blue",
            price: " 65999",
            },
            {
                id:9,
                category: "mobile",
                title: " Apple iPhone 14",
                imgSrc: "https://m.media-amazon.com/images/I/716fAVud8PL._SL1500_.jpg",
                amazoneLink:"http://amzn.to/3PuckZp",
                description:"Apple iPhone 14 (128 GB) - Blue",
                price: " 89999",
                },
                {
                    id:4,
                    category: "mobile",
                    title: " Apple iPhone 14",
                    imgSrc: "https://m.media-amazon.com/images/I/716fAVud8PL._SL1500_.jpg",
                    amazoneLink:"http://amzn.to/3PuckZp",
                    description:"Apple iPhone 14 (128 GB) - Blue",
                    price: " 89999",
                    },
                    {
                        id:5,
                        category: "mobile",
                        title: " Apple iPhone 14",
                        imgSrc: "https://m.media-amazon.com/images/I/716fAVud8PL._SL1500_.jpg",
                        amazoneLink:"http://amzn.to/3PuckZp",
                        description:"Apple iPhone 14 (128 GB) - Blue",
                        price: " 89999",
                        },
                        {
                            id:6,
                            category: "mobile",
                            title: " Apple iPhone 14",
                            imgSrc: "https://m.media-amazon.com/images/I/716fAVud8PL._SL1500_.jpg",
                            amazoneLink:"http://amzn.to/3PuckZp",
                            description:"Apple iPhone 14 (128 GB) - Blue",
                            price: " 89999",
                            },
                            {
                                id:7,
                                category: "mobile",
                                title: " Apple iPhone 14",
                                imgSrc: "https://m.media-amazon.com/images/I/716fAVud8PL._SL1500_.jpg",
                                amazoneLink:"http://amzn.to/3PuckZp",
                                description:"Apple iPhone 14 (128 GB) - Blue",
                                price: " 89999",
                                },
                                {
                                    id:8,
                                    category: "mobile",
                                    title: " Apple iPhone 14",
                                    imgSrc: "https://m.media-amazon.com/images/I/716fAVud8PL._SL1500_.jpg",
                                    amazoneLink:"http://amzn.to/3PuckZp",
                                    description:"Apple iPhone 14 (128 GB) - Blue",
                                    price: " 89999",
                                    },
]